### ISSUE TITLE
Aliases not saving between gaming sessions

### ISSUE THREAD

**Issue by MonolithTMA** [zambony/Gungnir#28]
Gungnir 1.5.1

I happily created and tested a bunch of aliases and they all worked great. I took a break and when I launched the game again they were all gone. /listaliases showed nothing. /listbinds showed all my binds, though. I checked in the BepInEx config directory and  saw zamboni.Gungnir_binds.txt, which had all my binds in it. Is there supposed to be a similar file for aliases?

**What command or feature were you using at the time?** /alias.

**Replication Procedure:** I tried it 6 times, each time launching the game, creating an alias, quitting, and relaunching. No dice.

**Screenshots or Logs:**

Here's part of the log. I will attach the whole thing.

[Info   : Unity Log] [Gungnir:CommandHandler.cs:1500] Running command listbinds
[Info   : Unity Log] [Gungnir:CommandHandler.cs:1500] Running command alias
[Info   : Unity Log] [Gungnir:CommandHandler.cs:157] Alias karve created for /give FineWood 30;/give DeerHide 10;/give Resin 20;/give BronzeNails 80
[Info   : Unity Log] [Gungnir:CommandHandler.cs:1500] Running command alias
[Info   : Unity Log] [Gungnir:CommandHandler.cs:157] Alias /start created for /nostam;/nores;/creative;/ghost;/noslide
[Info   : Unity Log] [Gungnir:CommandHandler.cs:1500] Running command listaliases
[Info   : Unity Log] 07/13/2022 13:54:58: UI Group status changed MenuRoot = True

[Info   : Unity Log] 07/13/2022 13:54:59: UI Group status changed MenuRoot = False
[LogOutput.log](https://github.com/zambony/Gungnir/files/9104784/LogOutput.log)

**Comment by zambony** [comment]
oh man I can't believe I missed that. another instance of me rushing to get a release out. simple fix, I'll put it up later.

**Comment by MonolithTMA** [comment]
It's all good. 😊
