### ISSUE TITLE
Add building health level to /repairbuilds

### ISSUE THREAD

**Issue by MonolithTMA** [zambony/Gungnir#35]
I used to use a Nexus mod called LeaveMyBaseAlone. The two features I liked were 1. Activating a ward would repair everything within a certain radius. /repairbuilds already does this. 2. It allowed you to set the health of a building, so you could set everything you build or repair to 1500 hp or whatever you want. It would be nice if I could do /repairbuilds 20 1500, etc. Thus allowing me to set the HP of structures higher than their vanilla levels. No big deal if it can't be done. [Leave My Base Alone](https://www.nexusmods.com/valheim/mods/392)

**Comment by zambony** [comment]
Sounds easy enough, maybe I'll see about making a special value that would make the structure unbreakable. Not sure if that could be persisted across restarts, but I'll look into it.

**Comment by zambony** [comment]
I'm attempting to find a solution that works in multiplayer, but I don't think I'll be able to. While I could make the game do anything you want in singleplayer, getting other players to agree upon the health of a structure seems to not be possible. There's only one "message" I can send to other players, which is to repair a structure.

That will repair the structure for other clients, but if they damage it, they're going to send the "damage" message to everyone else,, which will set the structure to what *they* think the health should be.

There's no message I can find that tells other clients to set a structure to a specific health. I'll keep looking though, maybe there's a way I can make it MP compatible in a different way.

**Comment by MonolithTMA** [comment]
Thanks for plugging away at it. You may want to check out [Aedenthorn's Building Damage Mod](https://www.nexusmods.com/valheim/mods/233). There is a GitHub link at the bottom of the page.

**Comment by zambony** [comment]
That is an interesting approach, though I'm not sure how well that works in this specific instance.

They basically intercept the damage message I was mentioning and then don't execute it. I could do the same and send back out a repair message or something similar to create an invincible structure, though it would only work while you're logged in.

I'm looking for a persistent way to set a building piece's health beyond what it allows, but in a way that synchronizes with other players. I'll think a bit more about the approach used by that mod to see if I can modify it.

**Comment by MonolithTMA** [comment]
I wish Hexxen/Hexxen Live had the code on GitHub; all I can find is a snippet from their Thunderstore page for the mod.

```
//get actual structure object from client and set health
 hview.GetZDO().Set("health", m_Structure.Value); 
//hardcode monsters targetting to remove player bases.
   m_monsterTargetRayMask = LayerMask.GetMask(new string[]
            {
             "Default",
             "static_solid",
             "Default_small",
            "vehicle"
            });
```

**Comment by zambony** [comment]
I don't know enough about Valheim's networking, so I was under the impression that just setting the `health` value of an object's ZDO would not work. I need some way to tell other players to also set it to that value, otherwise we'll have a mess of unsynchronized health values.

**Comment by MonolithTMA** [comment]
You're better off than me. Aside from a little HTML and CSS, I haven't done any kind of coding since OG Basic on a mainframe in college in the late 80s. I've used LeaveMyBaseAlone on my server, and I was able to bless any structure by repairing it regardless of who built it. I haven't used that mod in a while, though.

**Comment by zambony** [comment]
Seems I found a way to forcefully send the health value to other clients. This will be in the next update.

**Comment by MonolithTMA** [comment]
Awesome! Thanks!
