### ISSUE TITLE
Console flood on latest game version

### ISSUE THREAD

**Issue by BluePyros** [zambony/Gungnir#44]
**What version of Gungnir were you using?**
1.7.0

**What happened?**
Console flooded with the following error:

[Error  : Unity Log] MissingFieldException: Field 'Terminal.m_output' not found.
Stack trace:

**What command or feature were you using at the time?**
Launching the game and sitting at main menu.

**Replication Procedure:**
Launch game with BepInExPack Vers 5.4.1901 and Gungnir Vers 1.7.0.  Game Vers: 0.214.2 on Steam
No other mods installed.

**Screenshots or Logs:**
![Capture](https://user-images.githubusercontent.com/12477515/224743668-0317069c-9502-4fdd-95cb-1f4726042f2d.PNG)

**Comment by Unforgiven13** [comment]
+1

**Comment by zambony** [comment]
HMMM, okay, I probably just need to rebuild the mod with the latest game binaries. I'll have a fix up soon.

**Comment by zambony** [comment]
Oh, looks like they added a new module that changes how all the UI text in game works. Fun. It might be a bit before I get this fixed.
