### ISSUE TITLE
After Valheim Patch 0.216.9 Gungnir has a few issues

### ISSUE THREAD

**Issue by MonolithTMA** [zambony/Gungnir#47]
**What version of Gungnir were you using?** 1-7-1

**What happened?** Several errors as listed below.

[Error  : Unity Log] [Gungnir:CommandHandler.cs:1867] Something happened while running nomana, check the BepInEx console for more details.
[Error  : Unity Log] MethodAccessException: Method `Player.SetMaxEitr(single,bool)' is inaccessible from method `Gungnir.CommandHandler.ToggleMana(System.Nullable`1<bool>)'
Stack trace:
Gungnir.CommandHandler.ToggleMana (System.Nullable`1[T] enabled) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Gungnir.CommandHandler.Run (System.String text) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Gungnir.CommandHandler.<Register>b__70_3 (Terminal+ConsoleEventArgs args) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Terminal+ConsoleCommand.RunAction (Terminal+ConsoleEventArgs args) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::TryRunCommand>(Terminal,string,bool,bool)
Gungnir.Patch.PatchManager+CommandChainingPatch.Prefix (System.String& text) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::TryRunCommand>(Terminal,string,bool,bool)
(wrapper dynamic-method) Terminal.DMD<Terminal::InputText>(Terminal)
Terminal.SendInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.UpdateInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Console.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)

[Error  : Unity Log] [Gungnir:CommandHandler.cs:1867] Something happened while running repairbuilds, check the BepInEx console for more details.
[Error  : Unity Log] MissingMethodException: System.Collections.Generic.List`1<WearNTear> WearNTear.GetAllInstaces()
Stack trace:
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Gungnir.CommandHandler.Run (System.String text) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Gungnir.CommandHandler.<Register>b__70_3 (Terminal+ConsoleEventArgs args) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Terminal+ConsoleCommand.RunAction (Terminal+ConsoleEventArgs args) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::TryRunCommand>(Terminal,string,bool,bool)
(wrapper dynamic-method) Terminal.DMD<Terminal::InputText>(Terminal)
Terminal.SendInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.UpdateInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Console.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)

[Info   : Unity Log] [Gungnir:CommandHandler.cs:1859] Running command spawn
[Error  : Unity Log] [Gungnir:CommandHandler.cs:1867] Something happened while running spawn, check the BepInEx console for more details.
[Error  : Unity Log] MissingMethodException: int ZDO.GetPGWVersion()
Stack trace:
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <695d1cc93cca45069c528c15c9fdd749>:0)
Gungnir.CommandHandler.Run (System.String text) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Gungnir.CommandHandler.<Register>b__70_3 (Terminal+ConsoleEventArgs args) (at <3ff722c0d9f848778ba6f388e2aae786>:0)
Terminal+ConsoleCommand.RunAction (Terminal+ConsoleEventArgs args) (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
(wrapper dynamic-method) Terminal.DMD<Terminal::TryRunCommand>(Terminal,string,bool,bool)
(wrapper dynamic-method) Terminal.DMD<Terminal::InputText>(Terminal)
Terminal.SendInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.UpdateInput () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Terminal.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)
Console.Update () (at <2959d3c128e64c61a08dcc9bb6744ec3>:0)

**Comment by zambony** [comment]
Sounds like I need to rebuild with the latest game binaries. I'll investigate.

**Comment by MonolithTMA** [comment]
Thanks! Iron Gate fixed some spelling errors, which broke a bunch of mods.

**Comment by MonolithTMA** [comment]
I just noticed that the up and down arrow keys no longer cycle through previous commands.

**Comment by MonolithTMA** [comment]
The up and down keys are sometimes working?

**Comment by Vepixity** [comment]
I can confirm that the up and down arrows work for me 100% of the time. I get the same errors as you however when running those three commands

**Comment by zambony** [comment]
I have a new build I'll release later to fix the main errors, but I'm not sure why the command history is having trouble. It doesn't work at all for me, and it was actually a built-in Valheim feature, but I don't see that they changed that. I'll keep investigating, but it's more important to have the patch for the real issues out first.

**Comment by zambony** [comment]
Fixed in #48
